/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define YY_USES_REJECT
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 55
#define YY_END_OF_BUFFER 56
static yyconst short int yy_acclist[178] =
    {   0,
       48,   48,   56,   54,   55,   54,   55,   47,   54,   55,
       27,   54,   55,   26,   54,   55,    2,   54,   55,    3,
       54,   55,   22,   54,   55,   20,   54,   55,    8,   54,
       55,   21,   54,   55,   28,   54,   55,   23,   54,   55,
       52,   54,   55,   25,   54,   55,    9,   54,   55,   19,
       54,   55,   16,   54,   55,   18,   54,   55,   54,   55,
       54,   55,16435,    4,   54,   55,    5,   54,   55,   24,
       54,   55,   54,   55,16435,   54,   55,16435,   54,   55,
    16435,   54,   55,16435,   54,   55,16435,   54,   55,16435,
        6,   54,   55,    7,   54,   55,   55,   55,   48,   55,

       49,   55,   37,   55,   37,   55,   36,   37,   55,   37,
       55,   37,   55,   35,   37,   55,   31,   39,   52,   52,
       15,   13,   14,   34,   32, 8243,   50,16435,16435,16435,
       30, 8243,16435,16435,   11,16435,16435,   48,   35,   35,
       17,   33,16435,16435,16435,   11, 8243,16435,16435,   52,
    16435,   42, 8243,   41, 8243,16435,16435,   35,16435,16435,
    16435,   46,   10,   45, 8243,   11,16435,16435,   44, 8243,
       12,   38,    1,   53,   40,   29,   43
    } ;

static yyconst short int yy_accept[200] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    2,    3,    3,
        3,    3,    3,    4,    6,    8,   11,   14,   17,   20,
       23,   26,   29,   32,   35,   38,   41,   44,   47,   50,
       53,   56,   59,   61,   64,   67,   70,   73,   76,   79,
       82,   85,   88,   91,   94,   97,   98,   99,  101,  103,
      105,  107,  110,  112,  114,  117,  118,  118,  118,  118,
      118,  118,  118,  118,  118,  119,  119,  120,  120,  121,
      122,  123,  124,  125,  126,  126,  127,  128,  129,  130,
      131,  133,  134,  135,  137,  138,  139,  139,  140,  141,
      141,  141,  141,  141,  141,  141,  141,  141,  142,  142,

      143,  143,  143,  144,  145,  146,  148,  149,  150,  150,
      150,  150,  150,  150,  150,  150,  150,  150,  150,  151,
      152,  154,  156,  157,  158,  158,  159,  159,  159,  159,
      159,  159,  159,  159,  159,  160,  161,  162,  162,  163,
      163,  164,  164,  164,  164,  164,  164,  166,  168,  169,
      169,  169,  169,  169,  169,  169,  169,  171,  171,  171,
      171,  171,  171,  171,  172,  172,  172,  172,  172,  172,
      172,  172,  172,  172,  173,  173,  173,  173,  173,  173,
      173,  173,  173,  173,  173,  174,  175,  175,  175,  175,
      175,  176,  177,  177,  177,  177,  177,  178,  178

    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    2,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    3,    4,    5,    6,    1,    1,    1,    7,
        8,    9,   10,   11,   12,   13,   14,   15,   15,   15,
       15,   15,   15,   15,   15,   15,   15,   16,   17,   18,
       19,   20,    1,   21,   22,   22,   22,   22,   23,   22,
       22,   22,   22,   22,   22,   22,   22,   22,   22,   22,
       22,   22,   22,   22,   22,   22,   22,   22,   22,   22,
       24,    1,   25,   26,   22,    1,   27,   22,   28,   22,

       29,   22,   22,   22,   22,   22,   22,   30,   31,   32,
       33,   22,   22,   34,   35,   36,   37,   22,   38,   22,
       39,   22,   40,    1,   41,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
       42,   43,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,   44,    1,   45,    1,    1,   46,
       47,   48,   49,    1,    1,   50,   51,    1,    1,    1,
       52,    1,   53,    1,   54,    1,    1,    1,    1,   55,

       56,   57,   58,   59,    1,   60,    1,   61,    1,    1,
       62,   63,    1,   64,   65,   66,    1,    1,    1,    1,
        1,    1,    1,    1,   67,    1,   68,   69,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,   70,
        1,   71,    1,   72,    1,    1,   73,    1,   74,    1,
       75,    1,   76,    1,    1
    } ;

static yyconst int yy_meta[77] =
    {   0,
        1,    2,    1,    3,    1,    1,    4,    1,    1,    1,
        1,    1,    1,    1,    5,    6,    1,    1,    1,    1,
        1,    4,    4,    1,    1,    1,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1
    } ;

static yyconst short int yy_base[207] =
    {   0,
        0,    0,  381,  380,  379,  378,   75,   76,  377,  376,
       77,   87,  379,  386,  362,   56,  386,  361,  386,  386,
      386,  386,  386,  364,  360,  386,   73,  386,  386,  356,
       63,  386,   87,  113,  386,  386,  386,  146,   77,   80,
       74,   83,   84,  386,  386,  386,  142,    0,  158,  386,
      170,  386,   83,  358,  109,  386,  342,  302,  323,  325,
      312,  300,  320,  307,  386,  344,  102,  348,  114,  386,
      386,  386,  386,  386,  111,  386,  386,  212,  332,  103,
      386,  124,  102,  195,  104,    0,  346,  142,  143,  333,
      306,  307,  300,  311,  300,  297,  295,  386,  178,  386,

      345,  149,  130,  179,  183,  386,  159,  170,  242,  316,
      298,  283,  272,  278,  304,  297,  276,  328,  327,  193,
      386,  386,  129,  197,  326,  325,  304,  200,  334,  281,
      279,  270,  289,  284,  208,  182,  206,  290,  386,  265,
      386,  256,  257,  255,  257,  251,  386,  237,  239,  282,
      262,  269,  261,  259,  255,  315,  386,  283,  256,  243,
      252,  260,  249,  386,  273,  254,  253,  305,  246,  258,
      264,  226,  221,  386,  218,  193,  230,  204,  203,  259,
      258,  232,  197,  195,  386,  386,  225,  228,  212,  140,
      386,  386,   99,  106,   74,  117,  386,  386,  269,  275,

      281,  284,  290,  296,  299,  301
    } ;

static yyconst short int yy_def[207] =
    {   0,
      198,    1,  199,  199,  199,  199,  200,  200,  199,  199,
      201,  201,  198,  198,  198,  198,  198,  198,  198,  198,
      198,  198,  198,  198,  198,  198,  198,  198,  198,  198,
      198,  198,  202,  203,  198,  198,  198,  203,   38,   38,
       38,   38,   38,  198,  198,  198,  198,  204,  198,  198,
      198,  198,  198,  198,  198,  198,  198,  198,  198,  198,
      198,  198,  198,  198,  198,  198,  198,  198,  198,  198,
      198,  198,  198,  198,  205,  198,  198,   38,   38,   38,
      198,   38,   38,   38,   38,  204,  198,  198,  198,  198,
      198,  198,  198,  198,  198,  198,  198,  198,  198,  198,

      206,  205,   38,   38,   38,  198,   38,   38,  198,  198,
      198,  198,  198,  198,  198,  198,  198,  198,  198,   38,
      198,  198,   38,   38,  198,  198,  198,  198,  198,  198,
      198,  198,  198,  198,   38,   38,   38,  198,  198,  198,
      198,  198,  198,  198,  198,  198,  198,   38,   38,  198,
      198,  198,  198,  198,  198,  198,  198,  198,  198,  198,
      198,  198,  198,  198,  198,  198,  198,  198,  198,  198,
      198,  198,  198,  198,  198,  198,  198,  198,  198,  198,
      198,  198,  198,  198,  198,  198,  198,  198,  198,  198,
      198,  198,  198,  198,  198,  198,  198,    0,  198,  198,

      198,  198,  198,  198,  198,  198
    } ;

static yyconst short int yy_nxt[463] =
    {   0,
       14,   14,   15,   16,   17,   18,   19,   20,   21,   22,
       23,   24,   25,   26,   27,   28,   29,   30,   31,   32,
       33,   34,   34,   35,   36,   37,   34,   38,   39,   34,
       34,   40,   41,   42,   43,   34,   34,   34,   34,   44,
       45,   14,   14,   14,   14,   14,   14,   14,   14,   14,
       14,   14,   14,   14,   14,   14,   14,   14,   14,   14,
       14,   14,   14,   14,   14,   14,   14,   14,   14,   14,
       14,   14,   14,   14,   14,   14,   46,   46,   49,   49,
       51,   71,   72,   57,   52,   68,   53,   69,   53,   54,
       51,   55,   81,   73,   52,   87,   53,   88,   53,   54,

       58,   55,   74,   79,   59,   60,   79,   61,   82,   79,
       83,   84,   79,   79,   62,   63,   67,  100,   64,   77,
      197,   87,   85,   88,   99,  101,   68,   78,   69,  103,
       99,   79,   79,   79,   79,   79,  196,  105,  108,   79,
       79,   79,   79,   79,   79,   79,   79,   79,   79,   79,
       79,   79,   77,   79,   87,  100,   88,   89,   79,   79,
       78,  104,  136,  101,  120,  109,  195,   79,   79,   57,
      194,  109,   79,   79,   79,   80,   79,   79,   79,   79,
       79,   79,   79,   79,   79,   57,   58,  118,   79,  118,
       59,   60,  119,   61,  121,  123,  193,   57,  122,   79,

       62,   63,   58,  139,   64,  124,   59,   60,   79,   61,
      106,   79,   79,  148,   58,  192,   62,   63,   59,   60,
       64,   61,   79,  147,   79,  137,   79,  135,   62,   63,
      107,  191,   64,   78,   78,   79,  149,   79,   78,   78,
       78,   78,   78,   78,   78,   78,   78,   78,   78,   78,
       78,  125,  106,  125,  157,  190,  126,  189,  140,  188,
      187,  186,  185,  184,  183,  182,   79,  181,   79,   46,
       46,   46,   46,   46,   46,   48,   48,   48,   48,   48,
       48,   50,   50,   50,   50,   50,   50,   75,  180,   75,
       76,   76,  179,   76,   76,   76,   86,  178,  177,   86,

       86,   86,  102,  102,  101,  101,  176,  175,  174,  173,
      172,  171,  170,  169,  168,  167,  166,  165,  164,  163,
      162,  161,  160,  159,  158,  156,  155,  154,  153,  152,
      151,  150,  146,  145,  144,  143,  142,  141,  138,  126,
      126,  119,  119,  134,  133,  132,  131,  130,  129,  128,
      127,  100,  117,  116,  115,  114,  113,  112,  111,  110,
       89,   79,   67,   98,   97,   96,   95,   94,   93,   92,
       91,   90,   89,   70,   67,   66,   65,   56,  198,   47,
       47,   47,   47,   47,   47,   13,  198,  198,  198,  198,
      198,  198,  198,  198,  198,  198,  198,  198,  198,  198,

      198,  198,  198,  198,  198,  198,  198,  198,  198,  198,
      198,  198,  198,  198,  198,  198,  198,  198,  198,  198,
      198,  198,  198,  198,  198,  198,  198,  198,  198,  198,
      198,  198,  198,  198,  198,  198,  198,  198,  198,  198,
      198,  198,  198,  198,  198,  198,  198,  198,  198,  198,
      198,  198,  198,  198,  198,  198,  198,  198,  198,  198,
      198,  198
    } ;

static yyconst short int yy_chk[463] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    7,    8,    7,    8,
       11,   31,   31,   16,   11,   27,   11,   27,   11,   11,
       12,   11,   39,   33,   12,   53,   12,   53,   12,   12,

       16,   12,   33,   41,   16,   16,   39,   16,   40,   40,
       41,   42,   42,   43,   16,   16,   67,   75,   16,   34,
      196,   55,   43,   55,   67,   75,   69,   34,   69,   80,
       67,   83,   80,   85,   34,   34,  195,   83,   85,   34,
       34,   34,   34,   34,   34,   34,   34,   34,   34,   34,
       34,   34,   38,   82,   88,  102,   88,   89,  123,  103,
       38,   82,  123,  102,  103,   89,  194,   38,   38,   47,
      193,   89,   38,   38,   38,   38,   38,   38,   38,   38,
       38,   38,   38,   38,   38,   49,   47,   99,  107,   99,
       47,   47,   99,   47,  104,  107,  190,   51,  105,  108,

       47,   47,   49,  128,   47,  108,   49,   49,  104,   49,
       84,  136,  105,  136,   51,  189,   49,   49,   51,   51,
       49,   51,  120,  135,   84,  124,  124,  120,   51,   51,
       84,  188,   51,   78,   78,  137,  137,  135,   78,   78,
       78,   78,   78,   78,   78,   78,   78,   78,   78,   78,
       78,  109,  148,  109,  149,  187,  109,  184,  128,  183,
      182,  181,  180,  179,  178,  177,  148,  176,  149,  199,
      199,  199,  199,  199,  199,  200,  200,  200,  200,  200,
      200,  201,  201,  201,  201,  201,  201,  202,  175,  202,
      203,  203,  173,  203,  203,  203,  204,  172,  171,  204,

      204,  204,  205,  205,  206,  206,  170,  169,  168,  167,
      166,  165,  163,  162,  161,  160,  159,  158,  156,  155,
      154,  153,  152,  151,  150,  146,  145,  144,  143,  142,
      140,  138,  134,  133,  132,  131,  130,  129,  127,  126,
      125,  119,  118,  117,  116,  115,  114,  113,  112,  111,
      110,  101,   97,   96,   95,   94,   93,   92,   91,   90,
       87,   79,   68,   66,   64,   63,   62,   61,   60,   59,
       58,   57,   54,   30,   25,   24,   18,   15,   13,   10,
        9,    6,    5,    4,    3,  198,  198,  198,  198,  198,
      198,  198,  198,  198,  198,  198,  198,  198,  198,  198,

      198,  198,  198,  198,  198,  198,  198,  198,  198,  198,
      198,  198,  198,  198,  198,  198,  198,  198,  198,  198,
      198,  198,  198,  198,  198,  198,  198,  198,  198,  198,
      198,  198,  198,  198,  198,  198,  198,  198,  198,  198,
      198,  198,  198,  198,  198,  198,  198,  198,  198,  198,
      198,  198,  198,  198,  198,  198,  198,  198,  198,  198,
      198,  198
    } ;

static yy_state_type yy_state_buf[YY_BUF_SIZE + 2], *yy_state_ptr;
static char *yy_full_match;
static int yy_lp;
static int yy_looking_for_trail_begin = 0;
static int yy_full_lp;
static int *yy_full_state;
#define YY_TRAILING_MASK 0x2000
#define YY_TRAILING_HEAD_MASK 0x4000
#define REJECT \
{ \
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */ \
yy_cp = yy_full_match; /* restore poss. backed-over text */ \
yy_lp = yy_full_lp; /* restore orig. accepting pos. */ \
yy_state_ptr = yy_full_state; /* restore orig. state */ \
yy_current_state = *yy_state_ptr; /* restore curr. state */ \
++yy_lp; \
goto find_rule; \
}
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "han_compiler.l"
#define INITIAL 0
#line 2 "han_compiler.l"
	#include <stdio.h>
	#include <stdlib.h>
	#include <string.h>


	#include "y.tab.h"
	#include "han_compiler.hpp"

	void yyerror(const char*);
	int num_num = 0;
	int num_id = 0;
	int word_count = 0;
//	extern char*	yylval;头文件里面有
	void st();

//%token	<str>	LSCUR	RSCUR	LMCUR	RMCUR	LBCUR	RBCUR	COMMA	SEMICOLON
//%token	<argp>	arg
#define SINGLE_COMMENT 1

#define MULTI_COMMENT 2

#define STRING 3
	
#define STRING_TRANSM 4

#define ATTRIBUTE 5

#line 599 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 38 "han_compiler.l"


#line 753 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
		yy_state_ptr = yy_state_buf;
		*yy_state_ptr++ = yy_current_state;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 199 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			*yy_state_ptr++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 386 );

yy_find_action:
		yy_current_state = *--yy_state_ptr;
		yy_lp = yy_accept[yy_current_state];
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( yy_lp && yy_lp < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[yy_lp];
				if ( yy_act & YY_TRAILING_HEAD_MASK ||
				     yy_looking_for_trail_begin )
					{
					if ( yy_act == yy_looking_for_trail_begin )
						{
						yy_looking_for_trail_begin = 0;
						yy_act &= ~YY_TRAILING_HEAD_MASK;
						break;
						}
					}
				else if ( yy_act & YY_TRAILING_MASK )
					{
					yy_looking_for_trail_begin = yy_act & ~YY_TRAILING_MASK;
					yy_looking_for_trail_begin |= YY_TRAILING_HEAD_MASK;
					}
				else
					{
					yy_full_match = yy_cp;
					yy_full_state = yy_state_ptr;
					yy_full_lp = yy_lp;
					break;
					}
				++yy_lp;
				goto find_rule;
				}
			--yy_cp;
			yy_current_state = *--yy_state_ptr;
			yy_lp = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
case 1:
YY_RULE_SETUP
#line 40 "han_compiler.l"

	YY_BREAK
case 2:
YY_RULE_SETUP
#line 41 "han_compiler.l"
{puts("lex>>Find LSCUR");puts(yytext);yylval.argp=matchToken(1, Token::LSCUR, Bs,yytext);return LSCUR;}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 42 "han_compiler.l"
{puts("lex>>Find RSCUR");puts(yytext);yylval.argp=matchToken(1, Token::RSCUR, Bs,yytext);return RSCUR;}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 43 "han_compiler.l"
{puts("lex>>Find LMCUR");puts(yytext);yylval.argp=matchToken(1, Token::LMCUR, Bs,yytext);return LMCUR;}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 44 "han_compiler.l"
{puts("lex>>Find RMCUR");puts(yytext);yylval.argp=matchToken(1, Token::RMCUR, Bs,yytext);return RMCUR;}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 45 "han_compiler.l"
{puts("lex>>Find LBCUR");puts(yytext);yylval.argp=matchToken(1, Token::LBCUR, Bs,yytext);return LBCUR;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 46 "han_compiler.l"
{puts("lex>>Find RBCUR");puts(yytext);yylval.argp=matchToken(1, Token::RBCUR, Bs,yytext);return RBCUR;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 47 "han_compiler.l"
{puts("lex>>Find COMMA");puts(yytext);yylval.argp=matchToken(1, Token::COMMA, Bs,yytext);return COMMA;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 48 "han_compiler.l"
{puts("lex>>Find SEMICOLON");puts(yytext);yylval.argp=matchToken(1, Token::SEMICOLON, Bs,yytext);return SEMICOLON;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 50 "han_compiler.l"

	YY_BREAK
case 11:
YY_RULE_SETUP
#line 51 "han_compiler.l"
{puts("lex>>Find _return_");puts(yytext);yylval.argp=matchToken(1, Token::_return_, Bs,yytext);return _return_;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 54 "han_compiler.l"

	YY_BREAK
case 13:
YY_RULE_SETUP
#line 55 "han_compiler.l"
{puts("lex>>Find DENGYU");puts(yytext);yylval.argp=matchToken(1, Token::DENGYU, Bs,yytext);return DENGYU;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 56 "han_compiler.l"
{puts("lex>>Find TUIDAO");puts(yytext);yylval.argp=matchToken(1, Token::TUIDAO, Bs,yytext);return TUIDAO;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 57 "han_compiler.l"
{puts("lex>>Find JICHENG");puts(yytext);yylval.argp=matchToken(1, Token::JICHENG, Bs,yytext);return JICHENG;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 58 "han_compiler.l"
{puts("lex>>Find FUZHI");puts(yytext);yylval.argp=matchToken(1, Token::FUZHI, Bs,yytext);return FUZHI;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 59 "han_compiler.l"
{puts("lex>>Find SHUCHU");puts(yytext);yylval.argp=matchToken(1, Token::SHUCHU, Bs,yytext);return SHUCHU;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 60 "han_compiler.l"
{puts("lex>>Find DAYU");puts(yytext);yylval.argp=matchToken(1, Token::DAYU, Bs,yytext);return DAYU;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 61 "han_compiler.l"
{puts("lex>>Find XIAOYU");puts(yytext);yylval.argp=matchToken(1, Token::XIAOYU, Bs,yytext);return XIAOYU;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 62 "han_compiler.l"
{puts("lex>>Find JIA");puts(yytext);yylval.argp=matchToken(1, Token::JIA, Bs,yytext);return JIA;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 63 "han_compiler.l"
{puts("lex>>Find JIAN");puts(yytext);yylval.argp=matchToken(1, Token::JIAN, Bs,yytext);return JIAN;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 64 "han_compiler.l"
{puts("lex>>Find CHENG");puts(yytext);yylval.argp=matchToken(1, Token::CHENG, Bs,yytext);return CHENG;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 65 "han_compiler.l"
{puts("lex>>Find CHU");puts(yytext);yylval.argp=matchToken(1, Token::CHU, Bs,yytext);return CHU;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 66 "han_compiler.l"
{puts("lex>>Find MI");puts(yytext);yylval.argp=matchToken(1, Token::MI, Bs,yytext);return MI;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 67 "han_compiler.l"
{puts("lex>>Find DOTDOT");puts(yytext);yylval.argp=matchToken(1, Token::DOTDOT, Bs,yytext);return DOTDOT;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 68 "han_compiler.l"
{puts("lex>>Find CHANGEABLE");puts(yytext);yylval.argp=matchToken(1, Token::CHANGEABLE, Bs,yytext);return CHANGEABLE;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 69 "han_compiler.l"
{puts("lex>>Find PENDCHANGEABLE");puts(yytext);yylval.argp=matchToken(1, Token::PENDCHANGEABLE, Bs,yytext);return PENDCHANGEABLE;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 70 "han_compiler.l"
{puts("lex>>Find DOT");puts(yytext);yylval.argp=matchToken(1, Token::DOT, Bs,yytext);return DOT;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 72 "han_compiler.l"

	YY_BREAK
case 30:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp = yy_bp + 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 73 "han_compiler.l"
{puts("lex>>Find function_declare_attribute e");puts(yytext);yylval.argp=matchToken(1, Token::function_declare_attribute, Bs,yytext);return function_declare_attribute;}
	YY_BREAK
case 31:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp = yy_bp + 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 74 "han_compiler.l"
{puts("lex>>Find function_declare_attribute !");puts(yytext);yylval.argp=matchToken(1, Token::function_declare_attribute, Bs,yytext);return function_declare_attribute;}
	YY_BREAK
case 32:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp = yy_bp + 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 75 "han_compiler.l"
{puts("lex>>Find function_declare_attribute @");puts(yytext);yylval.argp=matchToken(1, Token::function_declare_attribute, Bs,yytext);return function_declare_attribute;}
	YY_BREAK
case 33:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp = yy_bp + 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 76 "han_compiler.l"
{puts("lex>>Find function_declare_attribute @{FUNCTIONNAME}");puts(yytext);yylval.argp=matchToken(1, Token::function_declare_attribute, Bs,yytext);return function_declare_attribute;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 77 "han_compiler.l"
{BEGIN ATTRIBUTE;puts("lex>>Find function_declare_attribute @");puts(yytext);}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 78 "han_compiler.l"
{puts("lex>>Find function_declare_attribute @(number)");puts(yytext);yylval.argp=matchToken(1, Token::function_declare_attribute, Sz,yytext);return function_declare_attribute;}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 79 "han_compiler.l"
{BEGIN INITIAL;puts("lex>>End function_declare_attribute @(number)");puts(yytext);}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 80 "han_compiler.l"
{puts("lex>>Unrecognized character in ATTRIBUTE");puts(yytext);}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 82 "han_compiler.l"

	YY_BREAK
case 39:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp = yy_bp + 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 83 "han_compiler.l"
{puts("lex>>Find changeable_attribute $");puts(yytext);yylval.argp=matchToken(1, Token::changeable_attribute, Bs,yytext);return changeable_attribute;}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 85 "han_compiler.l"

	YY_BREAK
case 41:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp = yy_bp + 3;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 86 "han_compiler.l"
{puts("lex>>Find variable_specific_attribute out");puts(yytext);yylval.argp=matchToken(1, Token::variable_specific_attribute, Bs,yytext);return variable_specific_attribute;}
	YY_BREAK
case 42:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp = yy_bp + 3;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 87 "han_compiler.l"
{puts("lex>>Find variable_specific_attribute new");puts(yytext);yylval.argp=matchToken(1, Token::variable_specific_attribute, Bs,yytext);return variable_specific_attribute;}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 89 "han_compiler.l"

	YY_BREAK
case 44:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp = yy_bp + 6;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 90 "han_compiler.l"
{puts("lex>>Find system_declare_attribute system");puts(yytext);yylval.argp=matchToken(1, Token::system_declare_attribute, Bs,yytext);return system_declare_attribute;}
	YY_BREAK
case 45:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp = yy_bp + 5;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 91 "han_compiler.l"
{puts("lex>>Find system_declare_attribute class");puts(yytext);yylval.argp=matchToken(1, Token::system_declare_attribute, Bs,yytext);return system_declare_attribute;}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 93 "han_compiler.l"

	YY_BREAK
case 47:
YY_RULE_SETUP
#line 94 "han_compiler.l"
{BEGIN STRING;puts("lex>>Find string start");puts("[");puts(yytext);puts("]");}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 95 "han_compiler.l"
{puts("lex>>Find string content");puts(yytext);yylval.argp=matchToken(1, Token::arg,Zf,yytext);return arg;}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 96 "han_compiler.l"
{BEGIN INITIAL;puts("lex>>Find string end");puts(yytext);}
	YY_BREAK
case 50:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 97 "han_compiler.l"
{
    if (strcmp(yytext, "if") == 0) {
	puts("lex>>Find IF");puts(yytext);
	yylval.argp = matchToken(1, Token::arg, Bs, yytext);
        return IF;
    } else if (strcmp(yytext, "elif") == 0||strcmp(yytext, "elseif") == 0) {
	puts("lex>>Find ELIF");puts(yytext);
	yylval.argp = matchToken(1, Token::arg, Bs, yytext);
        return ELIF;
    } else if (strcmp(yytext, "else") == 0) {
	puts("lex>>Find ELSE");puts(yytext);
        yylval.argp = matchToken(1, Token::arg, Bs, yytext);
        return ELSE;
    } else if (strcmp(yytext, "while") == 0) {
	puts("lex>>Find WHILE");puts(yytext);
        yylval.argp = matchToken(1, Token::arg, Bs, yytext);
        return WHILE;
    }else{
        puts("lex>>Find function name");puts(yytext);
	yylval.argp=matchToken(1, Token::arg,Zf,yytext);
	return arg;
    }
}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 120 "han_compiler.l"
{
    if (strcmp(yytext, "if") == 0) {
	puts("lex>>Find IF");puts(yytext);
	yylval.argp = matchToken(1, Token::arg, Bs, yytext);
        return IF;
    } else if (strcmp(yytext, "elif") == 0||strcmp(yytext, "elseif") == 0) {
	puts("lex>>Find ELIF");puts(yytext);
	yylval.argp = matchToken(1, Token::arg, Bs, yytext);
        return ELIF;
    } else if (strcmp(yytext, "else") == 0) {
	puts("lex>>Find ELSE");puts(yytext);
        yylval.argp = matchToken(1, Token::arg, Bs, yytext);
        return ELSE;
    } else if (strcmp(yytext, "while") == 0) {
	puts("lex>>Find WHILE");puts(yytext);
        yylval.argp = matchToken(1, Token::arg, Bs, yytext);
        return WHILE;
    }else{
        puts("lex>>Find arg");puts(yytext);
	yylval.argp=matchToken(1, Token::arg,Bs,yytext);
	return arg;
    }
}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 143 "han_compiler.l"
{puts("lex>>Find number");puts(yytext);yylval.argp=matchToken(1, Token::arg,Sz,yytext);return arg;}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 148 "han_compiler.l"

	YY_BREAK
case 54:
YY_RULE_SETUP
#line 149 "han_compiler.l"
{puts("lex>>Unrecognized character");puts(yytext);}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 150 "han_compiler.l"
ECHO;
	YY_BREAK
#line 1206 "lex.yy.c"
			case YY_STATE_EOF(INITIAL):
			case YY_STATE_EOF(SINGLE_COMMENT):
			case YY_STATE_EOF(MULTI_COMMENT):
			case YY_STATE_EOF(STRING):
			case YY_STATE_EOF(STRING_TRANSM):
			case YY_STATE_EOF(ATTRIBUTE):
				yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;
	yy_state_ptr = yy_state_buf;
	*yy_state_ptr++ = yy_current_state;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 199 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		*yy_state_ptr++ = yy_current_state;
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;

	register YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 199 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 198);
	if ( ! yy_is_jam )
		*yy_state_ptr++ = yy_current_state;

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 150 "han_compiler.l"


FILE * openfile(){

	printf("in openfile\n");
	FILE *fp;
	char ch;


	char * buffer = NULL;
	if((buffer = _getcwd( NULL, 0 )) == NULL)perror( "_getcwd error" );
	printf( "%s \n", buffer );


	if ((fp = fopen("D:\\Flex Windows\\FlexFiles\\HAN_COMPILER_AUTO_INTEGRATE_10_21\\codeTest1.txt", "r") )== NULL){
		printf("Cannot open file : codeTest1.txt\n");
		return NULL;
	}
	else{
        
		return fp;
	}

}

FILE * precompileFile(){
	printf("in precompileFile\n");
	FILE *fp;
	char ch;
	if ((fp = fopen("D:\\Flex Windows\\FlexFiles\\HAN_COMPILER_AUTO_INTEGRATE_10_21\\codeTest1out.txt", "w") )== NULL){
		printf("Cannot open file : codeTest1out.txt\n");
		return NULL;
	}
	else{
		return fp;
	}
}

int pretreate()
{

	//[^ \t\n]+       printf("执行REJECT");REJECT;

	yyin=openfile();
	yyout=stdout;

	if(yyin==NULL||yyout==NULL){ puts("lex>>cant open all File");system("pause");return 1;}
	//yylex();
	//printf("num = %d, id = %d\n", num_num, num_id);
	//因为此法分析为一循环，打印总数字数仅当使用文件操作时可读出
	//fclose(yyin);
	//fclose(yyout);
	//system("pause");
	return 0;
}

int yywrap()//此函数必须由用户提供,或者声明
{
    return 1;//返回1报告文件结尾0标记,为0则继续扫描
}
void st(){

	//strcpy(char *dest,char *src);
	strcpy(yylval.toString(),yytext);

}
